- name: Deploy web application
  hosts: webservers
  become: yes
  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: present
        update_cache: yes

    - name: Copy web files to server
      copy:
        src: "{{ webapp_source_dir }}/"
        dest: /var/www/html/
        mode: '0644'

    - name: Start Apache service
      service:
        name: apache2
        state: started
        enabled: yes
